# получать данные об объекте могут все
GET http://localhost:5050/author/
Accept: application/json
Content-Type: application/json

###

# получать данные об объекте могут все
GET http://localhost:5050/author/2/
Accept: application/json
Content-Type: application/json

###

# создавать объекты может только администратор и авторизованный пользователь
POST http://localhost:5050/author/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjgwMTA4OTIzLCJpYXQiOjE2ODAxMDg2MjMsImp0aSI6IjI2NGY2NDcxNWQ1NjQwNjY4NDQ1ODI5M2M0YTFmY2M4IiwidXNlcl9pZCI6NH0.8mB-CjBMbULFy9bvMXA1LnJWQyrHYW1OYUJiJ00EhqE

{
}

###

# обновлять объекты может только администратор и авторизованный пользователь
PUT http://localhost:5050/author/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjgwMTA5MzAzLCJpYXQiOjE2ODAxMDkwMDMsImp0aSI6IjE2MWFmZWRkYzFlNzRhYjZiMjc1MTM0MTZkMDBmYWFjIiwidXNlcl9pZCI6NH0.QefIPNU2Ms2I-Wz3nrDlfe81U0mb0U4WWwCD6VjuPzI

{
}

###

# обновлять объекты может только администратор и авторизованный пользователь
PATCH http://localhost:5050/author/2/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjgwMTA5NzY1LCJpYXQiOjE2ODAxMDk0MjEsImp0aSI6IjM0MmI0NWE5NmJiNzQyOTY4M2VjOGI4ZGE1ZWQyNzVhIiwidXNlcl9pZCI6NH0.JW2rCrfbhGjpaIuI8B8Xea5uXGk02sWLgl_uFw4VBIw

{
}

###

# удалять объекты может только администратор и авторизованный пользователь
DELETE http://localhost:5050/author/5/
Accept: application/json
Authorization: Bearer ...
