# получать данные об объекте может администратор и пользователь, который запрашивает свои данные
GET http://localhost:5050/reader/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjgxMTI0NDUzLCJpYXQiOjE2ODExMjQxNTMsImp0aSI6IjNmMzU3YTRkMjM3MDQ1NGFhNmYyMjFhMmVkZTEwMjllIiwidXNlcl9pZCI6NH0.QtzBOKs7ynvw-N-7YZiRSrFo7tPT-txThTPM5Z-GLoA

###

# получать данные об объекте может администратор и пользователь, который запрашивает свои данные
GET http://localhost:5050/reader/4
Accept: application/json
Authorization: Bearer

###

# создавать объекты могут все пользователи без авторизации
POST http://localhost:5050/reader/
Accept: application/json

{
  "phone_number": "78007657033",
  "active_books": [
    "Books some",
    "Книга1",
    "Какая-то книга",
    "hf7"
    ],
  "is_superuser": false,
  "username": "xnjckschjds",
  "first_name": "Кристина",
  "last_name": "Калинкина",
  "password": "bcndbhj17",
  "email": "Kristina1332@mail.ru",
  "is_staff": false,
  "is_active": true,
  "status": "active"
}

###

# обновлять объекты может администратор и пользователь, который изменяет свои данные
PUT http://localhost:5050/reader/4/
Accept: application/json
Authorization: Bearer

{
    "phone_number": 73473847384,
    "active_books": [
      "Books some"
    ],
    "password": "pbkdf2_sha256$390000$7WNraNMGM4TAlr2rLYCPxb$gTumXbiUr91BgUL4HhUBfk7CXOs5fzqu3Qv0ui1pDjY=",
    "last_login": "2023-03-29T07:38:01Z",
    "is_superuser": true,
    "username": "admin",
    "first_name": "Юлия",
    "last_name": "Гареева",
    "email": "Ghdsgh@yandex.ru",
    "is_staff": true,
    "is_active": true,
    "status": "inactive"
  }

###

# обновлять объекты может администратор и пользователь, который изменяет свои данные
PATCH http://localhost:5050/reader/4/
Accept: application/json
Authorization: Bearer

{
    "phone_number": 73473847384,
    "active_books": [
      "Books some"
    ],
    "password": "pbkdf2_sha256$390000$7WNraNMGM4TAlr2rLYCPxb$gTumXbiUr91BgUL4HhUBfk7CXOs5fzqu3Qv0ui1pDjY=",
    "last_login": "2023-03-29T07:38:01Z",
    "is_superuser": true,
    "username": "admin",
    "first_name": "Юлия",
    "last_name": "Князева",
    "email": "Ghdsgh@yandex.ru",
    "is_staff": true,
    "is_active": true,
    "status": "inactive"
  }

###

# удалять объекты может администратор и пользователь, который удаляет свои данные
DELETE http://localhost:5050/reader/9/
Accept: application/json
Authorization: Bearer
